In [1]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
# import pandas as shriniwas
import numpy as np

In [3]:
np.random.seed(50)   # for consistency

data = {
    'Student_id': range(1, 51),
    'Name': ['Student_' + str(i) for i in range(1, 51)],
    'Age': np.random.randint(18, 25, size=50),
    'Gender': np.random.choice(['Male', 'Female'], size=50),
    'Scores': [np.random.randint(50, 100, size=3).tolist() for _ in range(50)],
    'Attendance': np.random.randint(20, 100, size=50),
    'Grade': np.random.choice(['A', 'B', 'C', 'D', 'F'], size=50)
}

In [4]:
df = pd.DataFrame(data)
df.head()

   Student_id       Name  Age  Gender        Scores  Attendance Grade
0           1  Student_1   18  Female  [64, 54, 72]          55     B
1           2  Student_2   18    Male  [93, 69, 82]          23     C
2           3  Student_3   21  Female  [87, 90, 80]          84     F
3           4  Student_4   23  Female  [94, 93, 85]          66     C
4           5  Student_5   19    Male  [88, 77, 78]          32     F

In [5]:
def assign_grade(scores):
    avg_score = np.mean(scores)

    if avg_score > 90:
        return 'A'
    elif avg_score > 80:
        return 'B'
    elif avg_score > 70:
        return 'C'
    elif avg_score > 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Scores'].apply(assign_grade)
df.head()

   Student_id       Name  Age  Gender        Scores  Attendance Grade
0           1  Student_1   18  Female  [64, 54, 72]          55     D
1           2  Student_2   18    Male  [93, 69, 82]          23     B
2           3  Student_3   21  Female  [87, 90, 80]          84     B
3           4  Student_4   23  Female  [94, 93, 85]          66     A
4           5  Student_5   19    Male  [88, 77, 78]          32     B

In [6]:
df.loc[8, 'Age'] = np.nan
df.loc[29, 'Age'] = np.nan
df.loc[35, 'Age'] = np.nan

df.loc[11, 'Scores'] = None
df.loc[19, 'Scores'] = None

df.loc[9, 'Attendance'] = 105   # invalid
df.loc[15, 'Grade'] = 'Z'       # invalid

df.head(20)

    Student_id        Name   Age  Gender        Scores  Attendance Grade
0            1   Student_1  18.0  Female  [64, 54, 72]          55     D
1            2   Student_2  18.0    Male  [93, 69, 82]          23     B
2            3   Student_3  21.0  Female  [87, 90, 80]          84     B
3            4   Student_4  23.0  Female  [94, 93, 85]          66     A
4            5   Student_5  19.0    Male  [88, 77, 78]          32     B
5            6   Student_6  24.0    Male  [81, 90, 65]          96     C
6            7   Student_7  22.0  Female  [55, 97, 54]          73     D
7            8   Student_8  24.0    Male  [54, 68, 97]          41     C
8            9   Student_9   NaN    Male  [92, 67, 76]          98     C
9           10  Student_10  24.0  Female  [58, 96, 61]         105     C
10          11  Student_11  24.0  Female  [77, 77, 57]          65     C
11          12  Student_12  23.0    Male          None          53     D
12          13  Student_13  23.0    Male  [85, 53, 71]          74     D
13          14  Student_14  20.0  Female  [92, 53, 56]          70     D
14          15  Student_15  20.0    Male  [65, 81, 72]          63     C
15          16  Student_16  22.0    Male  [50, 61, 80]          52     Z
16          17  Student_17  24.0  Female  [83, 99, 64]          88     B
17          18  Student_18  21.0  Female  [76, 72, 96]          70     B
18          19  Student_19  22.0    Male  [87, 56, 80]          79     C
19          20  Student_20  21.0    Male          None          61     B

In [7]:
missing_values = df.isnull().sum()

invalid_attendance = df[(df['Attendance'] < 0) | (df['Attendance'] > 100)]
invalid_grades = df[~df['Grade'].isin(['A', 'B', 'C', 'D', 'F'])]

print("Missing values:\n", missing_values)
print("\nInvalid attendance:\n", invalid_attendance)
print("\nInvalid grades:\n", invalid_grades)

Missing values:
 Student_id    0
Name          0
Age           3
Gender        0
Scores        2
Attendance    0
Grade         0
dtype: int64

Invalid attendance:
    Student_id        Name   Age  Gender        Scores  Attendance Grade
9          10  Student_10  24.0  Female  [58, 96, 61]         105     C

Invalid grades:
     Student_id        Name   Age Gender        Scores  Attendance Grade
15          16  Student_16  22.0   Male  [50, 61, 80]          52     Z

In [8]:
# Fill missing Age with median
df['Age'] = df['Age'].fillna(df['Age'].median())

# Fix Attendance range
df['Attendance'] = df['Attendance'].apply(
    lambda x: 100 if x > 100 else (0 if x < 0 else x)
)

# Fix Scores
def fix_scores(scores):
    if not scores:
        return [0, 0, 0]
    return [max(0, min(100, s)) for s in scores]

df['Scores'] = df['Scores'].apply(fix_scores)

# Recalculate Grade
df['Grade'] = df['Scores'].apply(assign_grade)

df.head(20)

    Student_id        Name   Age  Gender        Scores  Attendance Grade
0            1   Student_1  18.0  Female  [64, 54, 72]          55     D
1            2   Student_2  18.0    Male  [93, 69, 82]          23     B
2            3   Student_3  21.0  Female  [87, 90, 80]          84     B
3            4   Student_4  23.0  Female  [94, 93, 85]          66     A
4            5   Student_5  19.0    Male  [88, 77, 78]          32     B
5            6   Student_6  24.0    Male  [81, 90, 65]          96     C
6            7   Student_7  22.0  Female  [55, 97, 54]          73     D
7            8   Student_8  24.0    Male  [54, 68, 97]          41     C
8            9   Student_9  21.0    Male  [92, 67, 76]          98     C
9           10  Student_10  24.0  Female  [58, 96, 61]         100     C
10          11  Student_11  24.0  Female  [77, 77, 57]          65     C
11          12  Student_12  23.0    Male     [0, 0, 0]          53     F
12          13  Student_13  23.0    Male  [85, 53, 71]          74     D
13          14  Student_14  20.0  Female  [92, 53, 56]          70     D
14          15  Student_15  20.0    Male  [65, 81, 72]          63     C
15          16  Student_16  22.0    Male  [50, 61, 80]          52     D
16          17  Student_17  24.0  Female  [83, 99, 64]          88     B
17          18  Student_18  21.0  Female  [76, 72, 96]          70     B
18          19  Student_19  22.0    Male  [87, 56, 80]          79     C
19          20  Student_20  21.0    Male     [0, 0, 0]          61     F

In [9]:
df.loc[5, 'Age'] = 35
df.loc[6, 'Age'] = 50
df.loc[7, 'Age'] = 65

df.loc[10, 'Attendance'] = 200
df.loc[12, 'Attendance'] = 175
df.loc[13, 'Attendance'] = 166

print("DataFrame with Outliers:\n")
print(df.iloc[5:20])

DataFrame with Outliers:

    Student_id        Name   Age  Gender        Scores  Attendance Grade
5            6   Student_6  35.0    Male  [81, 90, 65]          96     C
6            7   Student_7  50.0  Female  [55, 97, 54]          73     D
7            8   Student_8  65.0    Male  [54, 68, 97]          41     C
8            9   Student_9  21.0    Male  [92, 67, 76]          98     C
9           10  Student_10  24.0  Female  [58, 96, 61]         100     C
10          11  Student_11  24.0  Female  [77, 77, 57]         200     C
11          12  Student_12  23.0    Male     [0, 0, 0]          53     F
12          13  Student_13  23.0    Male  [85, 53, 71]         175     D
13          14  Student_14  20.0  Female  [92, 53, 56]         166     D
14          15  Student_15  20.0    Male  [65, 81, 72]          63     C
15          16  Student_16  22.0    Male  [50, 61, 80]          52     D
16          17  Student_17  24.0  Female  [83, 99, 64]          88     B
17          18  Student_18  21.0  Female  [76, 72, 96]          70     B
18          19  Student_19  22.0    Male  [87, 56, 80]          79     C
19          20  Student_20  21.0    Male     [0, 0, 0]          61     F

In [16]:
def handle_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df.loc[:, column] = df[column].apply(
        lambda x: upper_bound if x > upper_bound else (
            lower_bound if x < lower_bound else x
        )
    )

handle_outliers(df, 'Age')
handle_outliers(df, 'Attendance')

print(df.iloc[5:20])

    Student_id        Name   Age  Gender        Scores  Attendance Grade  \
5            6   Student_6  27.5    Male  [81, 90, 65]       96.00     C
6            7   Student_7  27.5  Female  [55, 97, 54]       73.00     D
7            8   Student_8  27.5    Male  [54, 68, 97]       41.00     C
8            9   Student_9  21.0    Male  [92, 67, 76]       98.00     C
9           10  Student_10  24.0  Female  [58, 96, 61]      100.00     C
10          11  Student_11  24.0  Female  [77, 77, 57]      144.75     C
11          12  Student_12  23.0    Male     [0, 0, 0]       53.00     F
12          13  Student_13  23.0    Male  [85, 53, 71]      144.75     D
13          14  Student_14  20.0  Female  [92, 53, 56]      144.75     D
14          15  Student_15  20.0    Male  [65, 81, 72]       63.00     C
15          16  Student_16  22.0    Male  [50, 61, 80]       52.00     D
16          17  Student_17  24.0  Female  [83, 99, 64]       88.00     B
17          18  Student_18  21.0  Female  [76, 72, 96]       70.00     B
18          19  Student_19  22.0    Male  [87, 56, 80]       79.00     C
19          20  Student_20  21.0    Male     [0, 0, 0]       61.00     F

    Scaled_Attendance
5            0.609218
6            0.424850
7            0.168337
8            0.625251
9            0.641283
10           1.000000
11           0.264529
12           1.000000
13           1.000000
14           0.344689
15           0.256513
16           0.545090
17           0.400802
18           0.472946
19           0.328657

In [17]:
df['Scaled_Attendance'] = (
    (df['Attendance'] - df['Attendance'].min()) /
    (df['Attendance'].max() - df['Attendance'].min())
)

print("Scaled Data:\n")
print(df[['Attendance', 'Scaled_Attendance']].head(20))

Scaled Data:

    Attendance  Scaled_Attendance
0        55.00           0.280561
1        23.00           0.024048
2        84.00           0.513026
3        66.00           0.368737
4        32.00           0.096192
5        96.00           0.609218
6        73.00           0.424850
7        41.00           0.168337
8        98.00           0.625251
9       100.00           0.641283
10      144.75           1.000000
11       53.00           0.264529
12      144.75           1.000000
13      144.75           1.000000
14       63.00           0.344689
15       52.00           0.256513
16       88.00           0.545090
17       70.00           0.400802
18       79.00           0.472946
19       61.00           0.328657